services:
  e2e:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/usr/app/specs
    depends_on:
      - reservations
      - auth
      - payments
      - notifications
      - mongodb

  reservations:
    image: reservations
    env_file:
      - ../apps/reservations/.env
    ports:
      - '3000:3000'

  auth:
    image: auth
    env_file:
      - ../apps/auth/.env
    ports:
      - '3001:3001'

  payments:
    image: payments
    env_file:
      - ../apps/payments/.env
    ports:
      - '3003:3003'

  notifications:
    image: notifications
    env_file:
      - ../apps/notifications/.env
    ports:
      - '3004:3004'

  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="test"
    ports:
      - '27017:27017'
    restart: always